export const foodItems = [
    {
        id: 1,
        category: "Fruits",
        name: "Red apple",
        price: "3",
        image: require("./assets/fruit-1.png"),
    },
    {
        id: 2,
        category: "Diary",
        name: "Milk and cheese",
        price: "25",
        image: require("./assets/diary-1.png"),
    },
    {
        id: 3,
        category: "Diary",
        name: "Cheese",
        price: "5",
        image: require("./assets/diary-2.png"),
    },
    {
        id: 4,
        category: "Diary",
        name: "Milk and cheese",
        price: "15",
        image: require("./assets/diary-3.png"),
    },
    {
        id: 5,
        category: "Fruits",
        name: "Passion fruit",
        price: "2",
        image: require("./assets/fruit-2.png"),
    },
    {
        id: 6,
        category: "Fruits",
        name: "Yello lemon",
        price: "1",
        image: require("./assets/fruit-3.png"),
    },
    {
        id: 7,
        category: "Fruits",
        name: "Green lemon",
        price: "2",
        image: require("./assets/fruit-4.png"),
    },
    {
        id: 8,
        category: "Fruits",
        name: "Avocado",
        price: "5",
        image: require("./assets/fruit-5.png"),
    },
    {
        id: 9,
        category: "Fruits",
        name: "Pineapple",
        price: "3",
        image: require("./assets/fruit-6.png"),
    },
    {
        id: 10,
        category: "Meat",
        name: "Lamb Meat",
        price: "32",
        image: require("./assets/meat-1.png"),
    },
    {
        id: 11,
        category: "Vegetables",
        name: "Bell Pepper Red",
        price: "6",
        image: require("./assets/tomatoes.png"),
    },
    {
        id: 12,
        category: "Meat",
        name: "Raw beef steak",
        price: "28",
        image: require("./assets/meat-3.png"),
    },
    {
        id: 13,
        category: "Meat",
        name: "Chicken meat",
        price: "42",
        image: require("./assets/meat-5.png"),
    },
    {
        id: 14,
        category: "Vegetables",
        name: "Arabic Ginger",
        price: "4",
        image: require("./assets/ginger.png"),
    },
    {
        id: 15,
        category: "Meat",
        name: "Beef flank",
        price: "35",
        image: require("./assets/meat-8.png"),
    },
    {
        id: 16,
        category: "Meat",
        name: "Bacon",
        price: "50",
        image: require("./assets/meat-6.png"),
    },
    {
        id: 17,
        category: "Vegetables",
        name: "Fresh Lettuce",
        price: "2",
        image: require("./assets/carbage.png"),
    },
    {
        id: 18,
        category: "Meat",
        name: "Raw beef",
        price: "40",
        image: require("./assets/meat-7.png"),
    },
    {
        id: 19,
        category: "Vegetables",
        name: "Butternut Squash",
        price: "8",
        image: require("./assets/squash.png"),
    },
    {
        id: 20,
        category: "Meat",
        name: "Fresh beef",
        price: "30",
        image: require("./assets/meat-2.png"),
    },
    {
        id: 21,
        category: "Vegetables",
        name: "Organic Carrot",
        price: "4",
        image: require("./assets/carrot.png"),
    },
    {
        id: 22,
        category: "Meat",
        name: "Fresh meat",
        price: "41",
        image: require("./assets/meat-4.png"),
    },
    {
        id: 23,
        category: "Vegetables",
        name: "Fresh Brocolli",
        price: "2",
        image: require("./assets/brocolli-1.png"),
    },
    
]